version: '3.4'

services:
  db:
    image: mariadb:10.2.25
    environment:
      MYSQL_USER : Vignup
      MYSQL_PASSWORD: AdminVignup
      MYSQL_ROOT_PASSWORD: secretR00tPassw0rd
      MYSQL_DATABASE: DataBase_VignupApi
    volumes:
      - data-volume:/data
  php:
    build:
      context: .
      target: api_php
    depends_on:
      - db
    volumes:
      - ./:/srv/api
      - ./docker/php/conf.d/dev.ini:/usr/local/etc/api.ini
  api:
    build:
      context: .
      target: api_nginx
    depends_on:
      - php
    volumes:
      - ./public:/srv/api/public:ro
    ports:
      - target: 80
        published: 8082
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: secretR00tPassw0rd

volumes:
  data-volume:

